version: '3.9'

services:  
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn webpythonapp.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - ./app:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=webpythonapp
      - POSTGRES_PASSWORD=webpythonapp
      - POSTGRES_DB=webpythonapp_prod
    env_file: 
      - ./.env.db.prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
    